name: dbt CI/CD

on:
  push:
    paths:
      - 'dbt/**'
      - '.github/workflows/dbt.yml'
      - '!dbt/analysis/**'

jobs:
  build:
    timeout-minutes: 15
    runs-on: self-hosted
    defaults:
      run:
        working-directory: dbt
    steps:
      - uses: actions/checkout@v2
      - name: Cache dbt dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: dbt/.venv
          key: ${{ runner.os }}-pip-dbt-${{ hashFiles('dbt/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-dbt
      - name: Install dbt dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -y python3-venv
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: Deploy models to dev
        env:
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
        run: |
          source .venv/bin/activate
          dbt seed --profiles-dir . --target dev
          dbt run --profiles-dir . --target dev
  test:
    timeout-minutes: 15
    needs: build
    runs-on: self-hosted
    defaults:
      run:
        working-directory: dbt
    steps:
      - uses: actions/checkout@v2
      - name: Cache dbt dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: dbt/.venv
          key: ${{ runner.os }}-pip-dbt-${{ hashFiles('dbt/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-dbt
      - name: Test models
        env:
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
        run: |
          source .venv/bin/activate
          dbt test --profiles-dir . --target dev
  deploy:
    timeout-minutes: 15
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: self-hosted
    defaults:
      run:
        working-directory: dbt
    steps:
      - uses: actions/checkout@v2
      - name: Cache dbt dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: dbt/.venv
          key: ${{ runner.os }}-pip-dbt-${{ hashFiles('dbt/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-dbt
      - name: Deploy models to prod
        env:
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
        run: |
          source .venv/bin/activate
          dbt seed --profiles-dir . --target prod
          dbt run --profiles-dir . --target prod
